In [1]:
# its a libarary using for manipulating Datsets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

C:\Users\dipali\AppData\Local\Temp\ipykernel_16444\1712497864.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
# Reading Datsets
sarcastic=pd.read_csv("../sarcastic.csv")

In [3]:
# Reading Datsets
non_sarcastic=pd.read_csv("../nonsarcastic.csv")

In [4]:
# Shape Of Datasets , means how many COlumn and Rows in Datasets
sarcastic.shape , non_sarcastic.shape

((6051, 11), (10128, 11))

In [5]:
#Top 5 Rows OF Datasets
sarcastic.head()

username                                           acctdesc  \
0  Lokeshk67004736                                                NaN   
1     prayagraj_AU  सत्यमेव जयते\n\nभगवा ध्वज भारत का ऐतिहासिक एवं...   
2       brand_dbm1  संस्थापक #भगवारक्षकटीम         राम राम दोस्तो🙏...   
3      Singh8Ankan  हिन्दू हूँ तो हिंदुत्व की बात ही करूँगा।जय श्र...   
4  PfCEAtft7vvZQRA  हम जिहादियों वामपंथियों कांग्रेसियों सपाइयों क...   

               location  following  followers  totaltweets  \
0                   NaN        632        380        14186   
1  Uttar Pradesh, India        208        192          677   
2      New Delhi, India       1029       3027         2908   
3                   NaN        800        105        52910   
4  Uttar Pradesh, India        674        171         4634   

         usercreatedts       tweetcreatedts  retweetcount  \
0  2020-02-26 16:57:31  2020-06-23 01:50:13            82   
1  2020-06-16 10:04:04  2020-06-23 00:46:17            82   
2  2014-11-16 17:44:40  2020-06-23 00:16:33            82   
3  2017-08-20 12:19:54  2020-06-22 23:55:11            82   
4  2020-03-09 06:44:20  2020-06-22 23:02:23            82   

                                                text hashtags  
0  हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...       []  
1  हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...       []  
2  हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...       []  
3  हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...       []  
4  हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...       []

In [6]:
non_sarcastic.head()

username                                           acctdesc  \
0        Jatsland  → \nℳera☺ Attitude मेरी 😎शान है,\n\nAur ℳerä द...   
1  lifestyleship7  Daily Lifestyle से संबंधित Educational, Busine...   
2     Benish_shex  I may not be perfect but atlest I m not fake.....   
3   Priyanshi_001  #My_life_my_rules_and_my_attitude.... \n\n#जी_...   
4       ParthikaH                                  I mAKe My OwN wAy   

                 location  following  followers  totaltweets  \
0  आपणो राजस्थान {नागौरी}        124       2884        70421   
1                   India          0          1           13   
2       Karachi, Pakistan        186        154         5232   
3                   🌹💫💕💫🌹          7       1111        51312   
4               India 🇮🇳          62          9           28   

         usercreatedts       tweetcreatedts  retweetcount  \
0  2014-05-08 05:11:58  2020-06-22 14:36:47             5   
1  2020-06-15 11:17:47  2020-06-22 14:29:26             0   
2  2016-05-26 08:01:53  2020-06-22 14:26:56             0   
3  2019-05-06 03:31:52  2020-06-22 14:23:01             5   
4  2019-06-18 18:17:23  2020-06-22 14:21:30             0   

                                                text  \
0  🍃🌼🍃🌼🍃🌼🍃🌼🍃🌼🍃\n\nकभी न बुझती है \nवो प्यास है #ज...   
1  डिप्रेशन के शुरुआती आठ लक्षण, उदाहरण और इलाज\n...   
2  @FaiziJee98 Aaj apki saalgirah hy nahi 🙊😛 or j...   
3  🍃🌼🍃🌼🍃🌼🍃🌼🍃🌼🍃\n\nकभी न बुझती है \nवो प्यास है #ज...   
4           #Happy rathyatra https://t.co/flLVnffvOJ   

                                            hashtags  
0  [{'text': 'जिंदगी', 'indices': [60, 67]}, {'te...  
1  [{'text': 'depression', 'indices': [75, 86]}, ...  
2  [{'text': 'happy', 'indices': [72, 78]}, {'tex...  
3  [{'text': 'जिंदगी', 'indices': [60, 67]}, {'te...  
4             [{'text': 'Happy', 'indices': [0, 6]}]

In [7]:
sarcastic=sarcastic[["text"]]
non_sarcastic=non_sarcastic[["text"]]

In [8]:
#Labelling

In [9]:
sarcastic["label"]=1
non_sarcastic["label"]=0

In [10]:
sarcastic.shape

(6051, 2)

In [11]:
# String Concatenate

In [12]:
df=pd.concat([sarcastic , non_sarcastic])

In [13]:
# Drop Duplicates

In [14]:
df = df.drop_duplicates(keep='first')

In [15]:
#sarcastic=sarcastic.drop_duplicates().reset_index().drop("index" , axis=1)

In [16]:
#non_sarcastic=non_sarcastic.drop_duplicates().reset_index().drop("index" , axis=1)

In [17]:
df

text  label
0     हमारे गांव में एक मास्टर जी रहते थे, वो मोहल्ल...      1
5     Dil hi saaf rakhlo... \nShakal ka to vaise bhi...      1
6     घोड़ो को ना मिली घास और गधे खा रहे चवनप्रास😃😃\...      1
7     पिछली सरकार के 10 साल के कार्यकाल  में 171 जवा...      1
8     "Akele aaye the akele hi jayengy" ye kahawat a...      1
...                                                 ...    ...
4044  https://t.co/HnIURjsvMT अंतर्राष्ट्रीय योग दिव...      0
6065  @Jaihindsonu59 @SinghChunni @SATYAPR27477125 क...      0
8093  https://t.co/qzgPRYlS1h प्रदेश में आज से कोरोन...      0
8095  Zyada achey b mat bano, yad rkho k meethey pha...      0
8096  zindagi ki yhi reet hai, haar k baad hi jeet h...      0

[1132 rows x 2 columns]

In [18]:
#Text Cleaning  , removing emoji from a Text
import re #regular expression

In [19]:
# Function For removing a Emojis From a Text
def remove_emojis(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [20]:
# applying function to remove a Emojis From a Text
df["text"]=df["text"].apply(remove_emojis)

In [21]:
#pip install ktrain

In [22]:
# Its a code for shuffling Datasets
df=df.sample(df.shape[0] , random_state=64)

In [23]:
# Value count of dependent Variable
df["label"].value_counts()

label
0    936
1    196
Name: count, dtype: int64

In [24]:
df

text  label
529   @Anujsingh20291 @NorbertElekes Shant Gadadhari...      1
551   ईश्वर की सबसे खूबसूरत धरोहर "पिता" के त्याग, ब...      0
257   @AqibWaheed_ @BBCUrdu @Junaid_PPP @MuqaddasRaz...      0
1775  #दुख से मत घबराना पंछी,ये जग दुखियों का मेला ह...      0
1061  ऐ मौसम है सुहाना... \n#Monsoon2020 #Happy #Mon...      0
...                                                 ...    ...
1700  @DrKumarVishwas दोस्तों को दुख ना हो..\nसोचकर ...      0
154   'आलू से सोना' बनाने की तकनीक खोजने वाले महान व...      1
513   .              Sirf  Smile  chhod Ke\n\n      ...      1
1677  पहले चाय,सिगरेट और तुम हमसफर थे मेरे,\nफिलहाल ...      0
563   बेमतलब सी इस दुनिया में वो ही हमारी शान है !\n...      0

[1132 rows x 2 columns]

In [25]:
import re

In [26]:
# Code for removing a Special Character
def remove_special_chars(input_string):
    chars_to_remove = ",@#"
    output_string = input_string.translate(str.maketrans('', '', chars_to_remove))
    return output_string

In [27]:
!pip install emoji

In [28]:
# Code For Removing Special Type of Emojis
import regex
def remove_emojis(text):
    emoji_pattern = regex.compile("[\p{Emoji}]")
    text_without_emojis = emoji_pattern.sub('', text)
    return text_without_emojis

In [29]:
# Applying That Function
df["text"]=df["text"].apply(remove_emojis)

In [30]:
df["text"]=df["text"].apply(remove_special_chars)

In [31]:
# Removing "\n" tag in text
df["text"]=df["text"].apply(lambda x:x.replace("\n", ""))

In [32]:
# Again Value Counts
df["label"].value_counts()

label
0    936
1    196
Name: count, dtype: int64

In [33]:
# Datasets is Imbalance With Dependent and Independent Variable  , So Making It Balance
sar=df[df["label"]==1]

In [34]:
sar_tst=sar.head(37)

In [35]:
sar_trn=sar.tail(159)

In [36]:
non_sar=df[df["label"]==0]

In [37]:
non_sar_tst=non_sar.head(187)

In [38]:
non_sar_trn=non_sar.tail(749)

In [39]:
test_df=pd.concat([sar_tst , non_sar_tst])

In [40]:
train_df=pd.concat([sar_trn , non_sar_trn])

In [41]:
train_df=train_df.sample(train_df.shape[0] , random_state=56)

In [42]:
# Sepraating for Train and Test algorithm
x_train=train_df["text"]
y_train=train_df["label"]

In [43]:
x_test=test_df["text"]
y_test=test_df["label"]

In [44]:
print(df[df["text"].isnull()])

Empty DataFrame
Columns: [text, label]
Index: []


In [45]:
# Importing Vectorizer For Converting Text Into Number
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
#Its a Object
cv=CountVectorizer()

In [47]:
x_train

931     HAPPY BIRTHDAY भारत के युवराज ओर मेरे नेता राह...
1766    आप जिंदगी मे कितने भी बड़े मुकाम क्यों नाहासिल...
711     Shabbat Shalom YHWH  Happy Shabbat spiritualar...
723     तुमको मिल जायेंगे बेहतर मुझसेमुझको मिल जायँगे ...
756     विश्वास का यह बंधन यूं ही बना रहेआपके जीवन में...
                              ...                        
544     AAKASHM  happy International Yoga DaySabhi ko ...
2002    arayanaenno NikhileshChanuअभिनेता सुशांत सिंह ...
1462    जिस प्रकार एक कुम्हार के थाप से मिट्टी भी सुंद...
232     IndinNederlands MEAIndia DrSJaishankar Hardeep...
1806    Post moterm karna par dil ko kuch mat karna..b...
Name: text, Length: 908, dtype: object

In [48]:
#Converted x_train Into Vector
x_train=cv.fit_transform(x_train)

In [49]:
x_train.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
#Converted x_test Into Vectorizer
#x_test=cv.transform(x_test)

In [51]:

# Save the trained CountVectorizer to a file
joblib.dump(cv, 'countvectorizer.pkl')


NameError: name 'joblib' is not defined

**Machine Learning Random Forest Classifier**

In [50]:
# Applying Machine Learning Algorithm 1st Random Forest Algorithm
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()

In [51]:
# Making Object of Random Forest and Training Model and Finding Accuracy
clf=RandomForestClassifier()
RFC_model=clf.fit(x_train , y_train )
y_pred=RFC_model.predict(x_test)
accuracy_score(y_test , y_pred)

0.96875

In [52]:
confusion_matrix(y_test , y_pred)

array([[187,   0],
       [  7,  30]], dtype=int64)

In [53]:
import joblib

In [54]:
joblib.dump(RFC_model, 'random_forest_model.pkl')


['random_forest_model.pkl']

**Support Vector Machine**

In [55]:
# Making Object of Support Vector MAchine  and Training Model and Finding Accuracy
from sklearn.svm import SVC
svc_classifier=SVC()
svc_model=svc_classifier.fit(x_train , y_train)
y_pred=svc_model.predict(x_test)
accuracy_score(y_test , y_pred)

0.9419642857142857

In [56]:
confusion_matrix(y_test , y_pred)

array([[187,   0],
       [ 13,  24]], dtype=int64)

In [58]:
import joblib

In [59]:
joblib.dump(svc_model, 'svc_model.pkl')


['svc_model.pkl']

**Decision Tree Classifier**

In [60]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [61]:
decision_clf=DecisionTreeClassifier()
dt_model=decision_clf.fit(x_train , y_train)
y_pred=decision_clf.predict(x_test)
accuracy_score(y_test , y_pred)

0.9821428571428571

In [62]:
confusion_matrix(y_test , y_pred)

array([[187,   0],
       [  4,  33]], dtype=int64)

In [63]:
joblib.dump(dt_model, 'dt_model.pkl')


['dt_model.pkl']

**Logistic Regression**

In [66]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()
lr_model=lr_model.fit(x_train  , y_train)
y_pred=lr_model.predict(x_test)
accuracy_score(y_test , y_pred)

0.9732142857142857

In [67]:
confusion_matrix(y_test , y_pred)

array([[187,   0],
       [  6,  31]], dtype=int64)

In [68]:
joblib.dump(lr_model, 'lr_model.pkl')


['lr_model.pkl']

**Now Deep learning Approches**

In [51]:
# Applying Long Sort Term Memory
train_df["label"].value_counts()

label
0    749
1    159
Name: count, dtype: int64

In [52]:
test_df

text  label
529   Anujsingh NorbertElekes Shant Gadadhari Bheen ...      1
578   Baar karte hain vo befikr hone ki Padhaya hai ...      1
544   RahulGandhi देश तो भारत के जवानों के साथ हो गय...      1
412   अरे सीमा पर तो रोज ही जवान मरते हैंअब क्या हर ...      1
123   'Bahar ki gandgi mat khaya kar jo kahana hai m...      1
...                                                 ...    ...
1522  "जिंदगी मे चुनौतियाँ हर किसी के हिस्से नहीं आत...      0
695   सूरज की किरणे तेज दे आपको खिलते हुए फूल_खुशबू ...      0
1022  pk सही में ये बादल छंट जायेंगे फिर दुख ना रहेग...      0
319   अरे योग कर ले भाईHappy  yoga  day https://t.co...      0
1236  Kuch haseen pal kuch haseen yaadein ️️️ pic in...      0

[224 rows x 2 columns]

In [53]:
import tensorflow as tf

In [54]:
tf.__version__

'2.10.0'

In [55]:
# Importing All Liberary
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [56]:
# Vocablary Maximum 5000
voc_size=5000

In [57]:
# Sperating Dependent and Independent Variable
x=df.drop("label" , axis=1)
y=df["label"]

In [58]:
msg=x.copy()

In [59]:
msg

text
529   Anujsingh NorbertElekes Shant Gadadhari Bheen ...
551   ईश्वर की सबसे खूबसूरत धरोहर "पिता" के त्याग बल...
257   AqibWaheed_ BBCUrdu Junaid_PPP MuqaddasRazzaq ...
1775  दुख से मत घबराना पंछीये जग दुखियों का मेला हैच...
1061  ऐ मौसम है सुहाना... Monsoon Happy Monsoon http...
...                                                 ...
1700  DrKumarVishwas दोस्तों को दुख ना हो..सोचकर दोस...
154   'आलू से सोना' बनाने की तकनीक खोजने वाले महान व...
513   .              Sirf  Smile  chhod Ke         B...
1677  पहले चायसिगरेट और तुम हमसफर थे मेरेफिलहाल चाय ...
563   बेमतलब सी इस दुनिया में वो ही हमारी शान है !कि...

[1132 rows x 1 columns]

In [60]:
# Importing Some Required Liberary
import nltk
import re
from nltk.corpus import stopwords

In [61]:
# Downloading Stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dipali\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [62]:
msg.reset_index(inplace=True)

In [63]:
# IMporting Stemmer
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

corpus=[]

In [64]:
# Making Corpus
for i in range(0 , len(msg)):
  review=msg["text"][i].lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words("english")]

  review=" ".join(review)
  corpus.append(review)

In [65]:
# Reg Ex Code For Removing Website
import re
def remove_links(text):
    pattern = r'https?://\S+|www\.\S+'
    text_without_links = re.sub(pattern, '', text)
    return text_without_links


In [66]:
# COde FOr removing Piunctuation
def remove_punctuation(text):
    punctuation = "!.,"
    for char in punctuation:
        text = text.replace(char, '')
    return text


In [67]:
 corpus=list(map(remove_links, corpus ))

In [68]:
corpus=list(map(remove_punctuation , corpus))

In [69]:
corpus

['anujsingh norbertelek shant gadadhari bheen shant understand sarcasm',
 'ईश्वर की सबसे खूबसूरत धरोहर "पिता" के त्याग बलिदान उनकी मेहनत तथा प्रेम को हम सच्चे हृदय से नमन करते हैंhappi father\' dayaawazehindhappyfathersday fathersday aawazehindnew drkumarvishwa adcrickettak mirchibollywoo journonikku ',
 'aqibwaheed_ bbcurdu junaid_ppp muqaddasrazzaq amjidkh pkadzon nai matlab khud asal samjh nai payi jese kayi aur log siasatdano ki pic laga kar happi father ki tweet kar rahe hen samjhi ke apn bhi kissi ki laga di hogi esli pichli tweet jo woh f talpur ke sath samjhi nai apk father hen es lie like nai kia',
 'दुख से मत घबराना पंछीये जग दुखियों का मेला हैचाहे भीड़ बहुत है जंगल में उड़ना तुझे ही अकेला हैजय श्री राम',
 'ऐ मौसम है सुहाना monsoon happi monsoon ',
 'पता नहीं आशुतोष की क्या मजबूरी है जो कंवल अंजना एयर सरदाना के साथ काम करना पड़ रहा है sad ',
 'सफलता तीन चीज़ो से मापी जाती हैं धन प्रसिद्धी और मन की शांति ।धन और प्रसिद्धी पाना आसान हैं ।“मन की शांति” केवल योग से मिलती हैं "योग:

In [70]:
corpus[1]

'ईश्वर की सबसे खूबसूरत धरोहर "पिता" के त्याग बलिदान उनकी मेहनत तथा प्रेम को हम सच्चे हृदय से नमन करते हैंhappi father\' dayaawazehindhappyfathersday fathersday aawazehindnew drkumarvishwa adcrickettak mirchibollywoo journonikku '

In [71]:
len(msg)

1132

In [72]:
onehot_rep=[one_hot(words , voc_size) for words in corpus]

In [73]:
# For New Word
#a=["ईश्वर की सबसे खूबसूरत धरोहर पिता के त्याग बलिदान उनकी मेहनत तथा प्रेम को हम सच्चे हृदय से नमन करते हैंhappi father' dayaawazehindhappyfathersday fathersday aawazehindnew drkumarvishwa adcrickettak mirchibollywoo journonikku"]

In [74]:
#[one_hot(words , voc_size) for words in a]

In [75]:
onehot_rep[1]

[4911,
 2148,
 3907,
 1893,
 4001,
 2359,
 1716,
 293,
 4950,
 3693,
 2939,
 3154,
 2416,
 1765,
 2379,
 3196,
 3720,
 3058,
 1184,
 3872,
 3523,
 2226,
 1383,
 3857,
 4105,
 1202,
 1042,
 2928,
 2216]

In [84]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [85]:
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(df['text'])
vocab_size = len(tokenizer.word_index) + 1

# Pad sequences
maxlen = 100  # Maximum sequence length
X = tokenizer.texts_to_sequences(df['text'])
X = pad_sequences(X, padding='post', maxlen=maxlen)



In [86]:
# Pad sequences
maxlen = 100  # Maximum sequence length
X = tokenizer.texts_to_sequences(df['text'])
X = pad_sequences(X, padding='post', maxlen=maxlen)

y = df['label']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the LSTM model
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length=maxlen))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



In [87]:
model.fit(X_train, y_train, epochs=5, batch_size=64, verbose=1)


Epoch 1/5
15/15 [==============================] - 4s 81ms/step - loss: 0.5906 - accuracy: 0.7878
Epoch 2/5
15/15 [==============================] - 1s 79ms/step - loss: 0.4597 - accuracy: 0.8298
Epoch 3/5
15/15 [==============================] - 1s 72ms/step - loss: 0.4574 - accuracy: 0.8298
Epoch 4/5
15/15 [==============================] - 1s 77ms/step - loss: 0.4599 - accuracy: 0.8298
Epoch 5/5
15/15 [==============================] - 1s 74ms/step - loss: 0.4640 - accuracy: 0.8298


In [88]:
model.save('lstm_model.h5')

**Embedding Representation**

In [77]:
# Taking Maximum word in sentence   which is 20
sent_length=100

In [81]:
embedded_docs = tokenizer.texts_to_sequences(df['text'])


NameError: name 'tokenizer' is not defined

In [78]:
embedded_docs=pad_sequences(onehot_rep , padding='post' , maxlen=sent_length)

In [79]:
print(onehot_rep)

[[2414, 2090, 1973, 3919, 1126, 1973, 2386, 4971], [4911, 2148, 3907, 1893, 4001, 2359, 1716, 293, 4950, 3693, 2939, 3154, 2416, 1765, 2379, 3196, 3720, 3058, 1184, 3872, 3523, 2226, 1383, 3857, 4105, 1202, 1042, 2928, 2216], [1277, 1265, 2382, 2160, 3934, 1897, 4604, 4868, 2371, 268, 4435, 2299, 4868, 2971, 3290, 1579, 3023, 2232, 3529, 1614, 1536, 2667, 4106, 2362, 3221, 1614, 3794, 4106, 1680, 2072, 3324, 3813, 780, 3214, 3122, 1614, 2667, 1787, 3646, 1908, 2970, 3794, 3349, 2887, 3548, 799, 3813, 4723, 3324, 4868, 2937, 3221, 2072, 3384, 3581, 3652, 4868, 422], [3884, 3058, 2351, 3593, 2249, 2339, 2993, 4875, 1961, 3262, 4901, 448, 2530, 3559, 1341, 2394, 2706, 2269, 1889, 742, 4730, 1830], [4501, 1634, 2530, 1547, 745, 2362, 745], [1661, 4325, 1102, 2148, 666, 839, 2530, 4591, 14, 256, 605, 3867, 1716, 890, 2845, 2890, 1485, 4955, 2530, 4007], [210, 2820, 1009, 3058, 3526, 2870, 2670, 853, 3839, 1191, 999, 2148, 1250, 3780, 1191, 3839, 1392, 1947, 2670, 1824, 2148, 4593, 3044, 117

In [80]:
print(embedded_docs)

[[   0    0    0 ... 1973 2386 4971]
 [   0    0    0 ... 1042 2928 2216]
 [   0    0    0 ... 3652 4868  422]
 ...
 [   0    0    0 ... 4267  457 1644]
 [   0    0    0 ...  890 4953 1357]
 [   0    0    0 ... 2359 3938   76]]


**creating LSTM model**

In [ ]:


# Build the LSTM model
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length=maxlen))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [83]:
embedded_vector_features=40
model=Sequential()
model.add(Embedding(voc_size , embedded_vector_features , input_length=20))
model.add(LSTM(100))

model.add(Dense(1 , activation='sigmoid'))
model.compile(loss='binary_crossentropy' , optimizer='adam' , metrics=['accuracy'])


In [84]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [85]:
embedded_docs.shape , y.shape

((1132, 20), (1132,))

In [86]:
import numpy as np

In [87]:
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
train_test_split(x_final , y_final , test_size=0.2)

[array([[2888, 4720, 3918, ...,  871, 1475, 4006],
        [2619, 3782, 2452, ..., 4443, 1946,  982],
        [   0,    0, 2819, ..., 4006, 2862,  119],
        ...,
        [4913, 2575,  192, ..., 1212, 1042, 2067],
        [ 853, 4126,  189, ..., 4798,  750, 1455],
        [   0,    0, 4754, ..., 4548, 4712, 3375]]),
 array([[   0,    0,    0, ..., 4894, 2160, 4708],
        [   0,    0,    0, ..., 3383, 4006, 4712],
        [   0,    0,    0, ..., 1093, 3488, 4488],
        ...,
        [ 978, 4358, 2916, ..., 1473, 2875, 2398],
        [  31, 2675, 1614, ..., 4712, 2004,   33],
        [   0,    0,    0, ..., 3627, 4028, 3492]]),
 array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 

In [90]:
x_final.shape

(1132, 20)

In [91]:
y_final.shape

(1132,)

In [92]:
x_train  , x_test , y_train  , y_test = train_test_split(x_final , y_final , test_size=0.2)

**Model Training**

In [93]:
model.fit(x_train , y_train  , validation_data=(x_test , y_test) , epochs=10 , batch_size=64)

Epoch 1/10
15/15 [==============================] - 4s 74ms/step - loss: 0.6179 - accuracy: 0.8088 - val_loss: 0.3558 - val_accuracy: 0.8722
Epoch 2/10
15/15 [==============================] - 0s 28ms/step - loss: 0.4282 - accuracy: 0.8155 - val_loss: 0.2951 - val_accuracy: 0.8722
Epoch 3/10
15/15 [==============================] - 0s 25ms/step - loss: 0.2926 - accuracy: 0.8265 - val_loss: 0.2013 - val_accuracy: 0.8943
Epoch 4/10
15/15 [==============================] - 1s 35ms/step - loss: 0.1259 - accuracy: 0.9591 - val_loss: 0.2066 - val_accuracy: 0.9383
Epoch 5/10
15/15 [==============================] - 1s 35ms/step - loss: 0.0623 - accuracy: 0.9978 - val_loss: 0.2675 - val_accuracy: 0.9075
Epoch 6/10
15/15 [==============================] - 0s 26ms/step - loss: 0.0320 - accuracy: 0.9989 - val_loss: 0.2992 - val_accuracy: 0.9163
Epoch 7/10
15/15 [==============================] - 0s 27ms/step - loss: 0.0128 - accuracy: 0.9989 - val_loss: 0.3412 - val_accuracy: 0.8987
Epoch 8/10
15

In [94]:
model.save('lstm_model.h5')

In [ ]:
from sklearn.metrics import accuracy_score

In [115]:
y_pred=model.predict(x_test)

8/8 [==============================] - 1s 6ms/step


In [117]:
y_pred=np.where(y_pred>0.1 ,1 , 0)

In [118]:
accuracy_score(y_test , y_pred)

0.8281938325991189

In [119]:
confusion_matrix(y_test , y_pred)

array([[170,  13],
       [ 26,  18]], dtype=int64)

In [120]:
x_train[0]

array([4598, 3771, 2473, 3459, 1623, 4811, 4693, 1030, 2371, 4112,  423,
        753, 4567,  731, 2520, 1357, 2527,   12, 2968, 1308])

In [121]:
x_test[0]

array([2173, 2118, 3933, 2954, 3170,   20, 4177, 1769, 4177, 1731, 2487,
       1008, 2085, 1198, 2180, 1872, 4973, 1686, 1308, 1070])

In [122]:
sam=model.predict([[  0, 2544, 2450, 3887,  556, 3055, 1013,  840, 1652, 4328, 4862,
          9, 1876, 2092, 4282, 2598, 1331,  821, 1130, 4119]])[0][0]

1/1 [==============================] - 0s 40ms/step


In [126]:
sam

0.0060732663

In [127]:
if sam>0.005:
  print("Sarcasam")
else:
  print("Non Sarcasam")

Sarcasam


In [128]:
model.save('Final_Model.h5')

In [129]:
# Save the CountVectorizer
joblib.dump(cv, 'count_vectorizer.pkl')

['count_vectorizer.pkl']